# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, verbose_name=b'Ba\xc5\x9fl\xc4\xb1k')),
                ('Content', models.TextField(verbose_name=b'\xc4\xb0\xc3\xa7erik')),
                ('PublishDate', models.DateTimeField(verbose_name=b'Yay\xc4\xb1nlanma Tarihi')),
            ],
        ),
    ]
