# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PublishDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Yay\xc4\xb1nlanma Tarihi'),
        ),
    ]
